web:
  image: htmlgraphic/apache:envoyer
  ports:
    - "80:80"
    - "443:443"
  environment:
    - NODE_ENVIRONMENT=dev
    - AUTHORIZED_KEYS="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCbKBlYPbK29pUUwtwRIIjwCtZNujOUb77qHIeohOMk+O8z0gEIgkUwVI3x91AlbhctgpQor3IIeFITwGgIKVo33WW64HI9Nfr2vGx9EAfl9CL9cfDj9M9u4EFOn8NkD/TQMH4d1Fslt59eyl4fSV62d98zJ8goJwrolXM5NlS3hss8FtXhN6bNM0V5nliPUrv/1//3ZoZ5p0inOI1xWNHcMEILGllG+yqaknH9yIk880WoCYZuR7q2ddE6mxrBeJFiyryW5nhsxmXfHnsDVGiLh1C3hltEXzZ0Bdj11jhJfgIcuKU1iUFZg3kKVjRAvrteBQA328s5+UJswV+NWFiH hosting@htmlgraphic.com"
  env_file:
    - .env
db:
  image: htmlgraphic/mysql:5.5
  expose:
    - "3306"
  environment:
    - ON_CREATE_DB=htmlgraphic
    - MYSQL_PASS=new_password
  ports:
    - "3306:3306"
db-data:
  image: busybox:latest
  volumes:
    - "/var/lib/mysql"
