web:
  image: htmlgraphic/apache:latest
  ports:
    - "80:80"
    - "443:443"
  environment:
    - NODE_ENVIRONMENT=dev
db:
  image: htmlgraphic/mysql:5.5
  expose:
    - "3306"
  environment:
    - ON_CREATE_DB=htmlgraphic
    - MYSQL_PASS=new_password
db-data:
  image: busybox
  volumes:
    - "/var/lib/mysql"
